import { formatPeriod, formatDate, formatTime, formatHours } from '../../data/payroll.js'

// Hand-to-the-accountant payroll sheet. Sits off-screen normally; the print
// CSS in index.css reveals only #print-area when the owner taps Print / PDF.
export default function PrintableSheet({ timesheet, settings, range }) {
  return (
    <div id="print-area" aria-hidden style={{ position: 'absolute', left: -99999, top: 0, width: '7.5in' }}>
      <div style={{ fontFamily: 'Arial, sans-serif', color: '#0A2540', padding: '0.25in' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', borderBottom: '3px solid #0A2540', paddingBottom: 8 }}>
          <div>
            <div style={{ fontSize: 22, fontWeight: 800 }}>Waterfront Solutions</div>
            <div style={{ fontSize: 12, color: '#13456E' }}>Payroll Timesheet</div>
          </div>
          <div style={{ textAlign: 'right', fontSize: 12 }}>
            <div><strong>Pay period:</strong> {formatPeriod(range)}</div>
            <div>
              Schedule: {settings.payPeriod} · Rounding:{' '}
              {settings.rounding === '15' ? 'nearest 15 min' : 'none'}
            </div>
          </div>
        </div>

        {timesheet.rows.map((row) => {
          const days = Object.keys(row.byDay).sort()
          return (
            <div key={row.worker.id} style={{ marginTop: 18, breakInside: 'avoid' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', background: '#0A2540', color: '#fff', padding: '4px 8px', fontWeight: 700 }}>
                <span>{row.worker.name}</span>
                <span>{formatHours(row.total)} hrs</span>
              </div>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12 }}>
                <thead>
                  <tr style={{ borderBottom: '1px solid #ccc', textAlign: 'left' }}>
                    <th style={th}>Date</th>
                    <th style={th}>Job</th>
                    <th style={th}>In</th>
                    <th style={th}>Out</th>
                    <th style={{ ...th, textAlign: 'right' }}>Hours</th>
                    <th style={th}>Flags</th>
                  </tr>
                </thead>
                <tbody>
                  {days.map((d) =>
                    row.byDay[d].shifts.map((s) => (
                      <tr key={s.id} style={{ borderBottom: '1px solid #eee' }}>
                        <td style={td}>{formatDate(s.clockIn.ts)}</td>
                        <td style={td}>{s.jobName}</td>
                        <td style={td}>{formatTime(s.clockIn.ts)}</td>
                        <td style={td}>{s.open ? 'on clock' : formatTime(s.clockOut.ts)}</td>
                        <td style={{ ...td, textAlign: 'right', fontWeight: 700 }}>{formatHours(s.hours)}</td>
                        <td style={{ ...td, fontSize: 10, color: '#b45309' }}>
                          {(s.flags || []).map((f) => f.label).join('; ')}
                        </td>
                      </tr>
                    )),
                  )}
                </tbody>
              </table>
            </div>
          )
        })}

        <div style={{ marginTop: 18, borderTop: '3px solid #0A2540', paddingTop: 8, display: 'flex', justifyContent: 'space-between', fontSize: 16, fontWeight: 800 }}>
          <span>CREW GRAND TOTAL</span>
          <span>{formatHours(timesheet.grandTotal)} hrs</span>
        </div>
        <div style={{ marginTop: 24, fontSize: 10, color: '#888' }}>
          Generated by Waterfront Solutions Crew Time Clock · times captured automatically at each punch.
        </div>
      </div>
    </div>
  )
}

const th = { padding: '4px 6px', fontSize: 11, color: '#13456E' }
const td = { padding: '4px 6px' }
